sonar.projectKey=romain-blanchot_montecarlo-portfolio-risk-gpu
sonar.organization=romain-blanchot

sonar.projectName=montecarlo-portfolio-risk-gpu

sonar.sources=src/portfolio_risk_engine
sonar.tests=tests
sonar.python.version=3.13

sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=\
  **/infrastructure/simulation/gpu_monte_carlo_engine.py,\
  **/infrastructure/simulation/gpu_accelerated_pipeline.py

sonar.sourceEncoding=UTF-8
