name: CI

# List :
# checkout
# setup python
# install deps

# format check
# lint

# unit tests
# integration tests

# sonar analysis

# build
# push artifcat

on:
    push:
        branches:
        - main
        - integration
    pull_request:
      branches:
        - main
        - integration

permissions:
    contents: read

jobs:
    build:
        name: Build and test
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v6

        - name: Set up Python
          uses: actions/setup-python@v6
          with:
            python-version: 3.13
            cache: pip


        - name: Install dependencies
          run: python -m pip install --upgrade pip && pip install -r requirements-dev.txt

        - name: Run tests
          run: pytest tests


    - name: Install build dependencies
      run: python -m pip install --upgrade build

    - name: Build
      run: python -m build

    - uses: actions/upload-artifact@v7
      with:
        name: artifacts
        path: dist
        if-no-files-found: error

